Lab2 not finished
Roclh/blps pull request #17
Opened 2023-03-29 16:41 UTC by bilguuk124

2023-04-11 22:06 UTC, Roclh requested changes
Очень много всего нужно сделать, могу сам поправить но только с утра, сейчас сил нету

2023-04-11 22:06 UTC, Roclh commented on src/main/java/com/roclh/blps/config/JwtAuthenticationFilter.java
> +            UserDetails userDetails = this.userDetailsService.loadUserByUsername(username);
Логика валидации пользователя размазана по всему проекту, возможно все связанные с безопасностью классы стоит закинуть в папку security

2023-04-12 12:04 UTC, bilguuk124 commented on src/main/java/com/roclh/blps/controllers/ArticleController.java
> +    @PutMapping("/up")
Это я хотел транзакцию сделать 😂

2023-04-12 12:09 UTC, bilguuk124 commented on src/main/java/com/roclh/blps/utils/AccountIdGenerator.java
> +    private static Long Id = 1L;
У нас на варианте было указано что информации юзеров хранить в файле.
А с файлами jpa не работает по моему. А нужно айди генерировать

2023-04-12 12:11 UTC, bilguuk124 commented on src/main/java/com/roclh/blps/entities/Account.java
> +    @JacksonXmlProperty(isAttribute = true)
На варианте написано

2023-04-12 12:17 UTC, bilguuk124 commented on src/main/java/com/roclh/blps/database/AccountDatabase.java
> +
не понял

2023-04-12 12:24 UTC, bilguuk124 commented on src/main/java/com/roclh/blps/controllers/AccountController.java
> +    @PostMapping("/admin-register")
Давай

2023-04-12 13:17 UTC, bilguuk124 commented on src/main/java/com/roclh/blps/controllers/ArticleController.java
> +public class ArticleController {
Сохраним этот совет в тудушку но пока не особо нужна

2023-04-12 13:21 UTC, bilguuk124 commented on src/main/java/com/roclh/blps/config/JwtAuthenticationFilter.java
> +            UserDetails userDetails = this.userDetailsService.loadUserByUsername(username);
Сделано

2023-04-26 16:37 UTC, merged