Bilguun1
Roclh/blps pull request #6
Opened 2023-03-01 15:40 UTC by bilguuk124

2023-03-02 16:51 UTC, Roclh requested changes
Вообще я бы оставил только todo.md с этого пр-а, потому что сваггер мы будем полностью по гайду этого чела настраивать

2023-03-02 16:51 UTC, Roclh commented on src/main/java/com/roclh/blps/TestData/StudopediaArticleConfig.java
> +//@Configuration
Replace commented full file with just commenting this annotation

2023-03-02 16:51 UTC, Roclh commented on src/main/java/com/roclh/blps/controllers/StudopediaController.java
> +    private static final Logger log = LoggerFactory.getLogger(StudopediaController.class);
А бля забыл мы же русские, ну тут надо вернуть лог менеджер

2023-03-02 16:51 UTC, Roclh commented on src/main/java/com/roclh/blps/controllers/StudopediaController.java
> +        log.info("Initializing Studopedia Co    ntroller");
интересное изменение

2023-03-21 10:12 UTC, bilguuk124 commented on src/main/java/com/roclh/blps/controllers/StudopediaController.java
> +        log.info("Initializing Studopedia Co    ntroller");
Ахахах это самое главное изменение нашего реквеста

2023-03-21 10:16 UTC, closed without merging